version: '3.8'

services:
  lapor-tanas:
    build: .
    container_name: lapor-tanas-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./.wwebjs_auth:/usr/src/app/.wwebjs_auth
      - ./data:/usr/src/app/data
      - ./public/uploads:/usr/src/app/public/uploads
    environment:
      - PORT=3000
      - NODE_ENV=production
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=lapor
